title: 'Heliophysics System Observatory'
author: Barbara J Thompson and Amr Alshatnawi 

logo: ../css/logo.png

html: 
  favicon: logo.png
  home_page_in_navbar : true
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true

repository:
  url: "https://github.com/AmrAlshatnawi/HSOConnect"
  branch: master
  path_to_book: site

latex:
  latex_engine              : xelatex

execute:
  execute_notebooks         : off

launch_buttons:
  binder             : true
  binderhub          : true
  binderhub_url      : off
  jupyterhub         : true
  thebe              : true
  colab              : true

sphinx:
  config:
    html_show_copyright: true
    myst_amsmath_enable: true
